# **Average gene expression and chromatin accessibility**

## **Introduction**

The `average` function is designed to return a *Pandas.DataFrame* that represents *gene expression* or c*hromatin accessibility* across various cell types for selected features. This tutorial demonstrates several possible applications of the `average` function.

## **Prerequisite**

In [ ]:
import atlasapprox

api = atlasapprox.API()

For detailed initial setup instructions, refer to the [Quick Start Tutorial](link to quick_start).

## **1 Get average gene expression**

This example illustrates a simple application of the `average` function, which allows you to calculate the *average gene expression* for selected genes,  within a specific organ of an organism.

The following example shows how to get the average expression of four genes (*TP53*, *KRAS*, *EGFR*, *ALK*) in the human lung:

In [3]:
avg_gene_expr_lung = api.average(
    organism = "h_sapiens", 
    organ = "lung", 
    features = ["TP53", "KRAS", "EGFR", "ALK"], 
    # measurement_type = 'gene_expression'
)

# Display the result
display(avg_gene_expr_lung)

,neutrophil,basophil,monocyte,macrophage,dendritic,B,plasma,T,NK,plasmacytoid,...,capillary,CAP2,lymphatic,fibroblast,alveolar fibroblast,smooth muscle,vascular smooth muscle,pericyte,mesothelial,ionocyte
TP53,0.054815,0.119978,0.327787,0.132754,0.238697,0.178123,0.038301,0.202786,0.239634,0.074571,...,0.219169,0.126632,0.254856,0.175867,0.160920,0.110756,0.193365,0.252695,0.152536,0.227391
KRAS,1.529643,0.436303,0.977728,0.489622,0.443576,0.562167,0.243355,0.826480,0.767580,0.467747,...,1.357422,1.346849,0.794639,0.249971,0.388602,0.582125,0.251247,0.708356,0.319821,0.714599
EGFR,0.016721,0.024823,0.028325,0.011413,0.000949,0.138468,0.031597,0.064145,0.051909,0.000000,...,0.579046,0.736705,0.085129,0.666291,0.720418,0.670286,0.528496,0.980535,0.225700,2.810568
ALK,0.000000,0.000000,0.001285,0.013633,0.000000,0.000000,0.000000,0.002077,0.000000,0.000000,...,0.001188,0.000000,0.000000,0.000689,0.004787,0.000000,0.000000,0.000000,0.000000,0.000000

## **4.1 Get available organisms**

In [38]:
organisms = api.organisms()

print("This is the available organisms under gene expression measurement type:")
display(organisms)

This is the available organisms under gene expression measurement type:

{'gene_expression': ['a_queenslandica',
  'a_thaliana',
  'c_elegans',
  'c_gigas',
  'c_hemisphaerica',
  'd_melanogaster',
  'd_rerio',
  'f_vesca',
  'h_miamia',
  'h_sapiens',
  'i_pulchra',
  'l_minuta',
  'm_leidyi',
  'm_murinus',
  'm_musculus',
  'n_vectensis',
  'o_sativa',
  'p_crozieri',
  'p_dumerilii',
  's_lacustris',
  's_mansoni',
  's_mediterranea',
  's_pistillata',
  's_purpuratus',
  't_adhaerens',
  't_aestivum',
  'x_laevis',
  'z_mays']}

Or you can search if the organism you are looking for in included in API.

In [36]:
aim_organism = 'h_sapiens'

if aim_organism in organisms['gene_expression']:
    print(f"{aim_organism} is available.")
else:
    print(f"{aim_organism} is NOT available.")

h_sapiens is available.

## **4.2 Get available human organs**

In [49]:
# Check all available cell types in human lung
human_organs = api.organs(organism='h_sapiens')

display(human_organs)

['bladder',
 'blood',
 'colon',
 'eye',
 'fat',
 'gut',
 'heart',
 'kidney',
 'liver',
 'lung',
 'lymphnode',
 'mammary',
 'marrow',
 'muscle',
 'pancreas',
 'prostate',
 'salivary',
 'skin',
 'spleen',
 'thymus',
 'tongue',
 'trachea',
 'uterus']

Also, you can search if the organ you are interested in is available:

In [41]:
aim_organ = 'lung'

if aim_organ in human_organs:
    print(f"{aim_organ} is available.")
else:
    print(f"{aim_organ} is NOT available.")

lung is available.

## **4.4 Get available cell types**

In [42]:
celltypes_human_lung = api.celltypes(organism='h_sapiens', organ='lung', measurement_type='gene_expression')
display(celltypes_human_lung)

['neutrophil',
 'basophil',
 'monocyte',
 'macrophage',
 'dendritic',
 'B',
 'plasma',
 'T',
 'NK',
 'plasmacytoid',
 'goblet',
 'AT1',
 'AT2',
 'club',
 'ciliated',
 'basal',
 'serous',
 'mucous',
 'arterial',
 'venous',
 'capillary',
 'CAP2',
 'lymphatic',
 'fibroblast',
 'alveolar fibroblast',
 'smooth muscle',
 'vascular smooth muscle',
 'pericyte',
 'mesothelial',
 'ionocyte']

Also you can ask if your aming celltype is included:

In [44]:
aim_celltype = 'NK'

if aim_celltype in celltypes_human_lung:
    print(f"{aim_celltype} cell is available.")
else:
    print(f"{aim_celltype} cell is NOT available.")

NK cell is available.

## **4.3 Get available genes of human**

In [45]:
human_genes = api.features(organism='h_sapiens')
display(human_genes)

Index(['A1BG', 'A1BG-AS1', 'A1CF', 'A2M', 'A2M-AS1', 'A2ML1', 'A2ML1-AS1',
       'A2ML1-AS2', 'A2MP1', 'A3GALT2',
       ...
       'ZXDA', 'ZXDB', 'ZXDC', 'ZYG11A', 'ZYG11AP1', 'ZYG11B', 'ZYX', 'ZYXP1',
       'ZZEF1', 'hsa-mir-1253'],
      dtype='object', name='features', length=58870)

Also you can search if your interested gene is included:

In [48]:
aim_gene = 'MTRNR2L12'

if aim_gene in human_genes:
    print(f"{aim_gene} gene is available.")
else:
    print(f"{aim_gene} gene is NOT available.")

MTRNR2L12 gene is available.

## **3 Get top 3 marker genes**

markers function allows you to get the top 10 marker genes in specified organ.

In [26]:
markers_in_human_lung = api.markers(
    organism="h_sapiens", 
    organ="liver", 
    cell_type="neutrophil", 
    number="3")

display(markers_in_human_lung)

['MTRNR2L12', 'AL512646.1', 'FP671120.5']

## **2 Show average gene expression in multiple organs across all cell type**

This example calculates and displays the *average gene expression* for five specified genes (*'MTRNR2L12'*, *'AL512646.1'*, *'FP671120.5'*) across three human organs: *'bladder'*, *'blood'*,*'colon'*. The gene expression data for each organ is sorted by the values in *neutrophils* and *T cells* before being displayed.

In [27]:
# To select an organ_list, you can specify the desired organ.
# To display all available organs, try the following command:
# organ_list = api.organs("h_sapiens")
organ_list = ['bladder','blood','colon']

# loop through organ_list and display the results
for organ in organ_list: 
    avg_gene_expr = api.average(
        organism = "h_sapiens", 
        organ = organ, 
        # features = ["TP53", "KRAS", "EGFR", "ALK"], 
        features = ['MTRNR2L12', 'AL512646.1', 'FP671120.5'],
        # measurement_type = 'gene_expression'
    )
    
    # Display result
    print(f'Everage gene expression in human {organ}:')
    display(avg_gene_expr)

Everage gene expression in human bladder:

,mast,macrophage,B,plasma,T,NK,plasmacytoid,urothelial,venous,capillary,lymphatic,fibroblast,smooth muscle,pericyte
MTRNR2L12,0.040105,0.121860,0.132304,0.016499,0.013802,0.052788,0.002277,0.059001,0.092321,0.041095,0.083313,0.058918,0.034633,0.051836
AL512646.1,0.035943,0.038304,0.022516,0.003811,0.000003,0.010509,0.009106,0.009846,0.013450,0.000868,0.019044,0.003351,0.013949,0.001608
FP671120.5,0.037544,0.052078,0.109802,0.039630,0.001136,0.003897,0.038702,0.061551,0.125526,0.004339,0.208300,0.036039,0.009927,0.024970

Everage gene expression in human blood:

,HSC,neutrophil,basophil,myeloid,monocyte,macrophage,dendritic,erythrocyte,B,plasma,T,NK,plasmacytoid,platelet
MTRNR2L12,0.042015,0.020157,0.04958,0.0,0.064458,0.003231,0.035253,0.006407,0.024542,0.026737,0.021280,0.020722,0.0,0.165943
AL512646.1,0.001165,0.036670,0.00000,0.0,0.145861,0.000000,0.000000,0.004813,0.004529,0.040637,0.002428,0.000875,0.0,0.002268
FP671120.5,0.058010,0.016955,0.00000,0.0,0.068890,0.013620,0.000000,0.008137,0.086548,0.006233,0.122227,0.037445,0.0,0.080209

Everage gene expression in human colon:

,neutrophil,mast,monocyte,B,plasma,T,goblet,brush,crypt,transit amp,enterocyte,paneth,venous,capillary,fibroblast,enteroendocrine
MTRNR2L12,0.878699,0.0,0.025914,0.030038,0.012355,0.024335,2.114801,2.636931,0.351932,0.056754,0.674713,0.123892,0.000000,0.0,0.060827,0.218810
AL512646.1,0.055621,0.0,0.000000,0.000000,0.000000,0.000000,0.035407,0.328170,0.006913,0.000898,0.014697,0.000000,0.000000,0.0,0.000169,0.001798
FP671120.5,0.040737,0.0,0.004727,0.003165,0.000000,0.002037,0.422802,1.238326,0.056464,0.006978,0.048138,0.000000,0.085853,0.0,0.005391,0.000000

### **Output**

The `avg_gene_expr_lung` variable contains a Pandas DataFrame where:
* Each row represents a gene.
* Each column corresponds to a cell type.
* The values indicate the average gene expression, measured in counts per ten thousand (cptt).

## **6 Filtering data by selected cell types**

This example demonstrates how to filter `avg_gene_expr_lung` to display only the selected cell types (*neutrophil*, *macrophage*, *plasma*).

In [120]:
# Filter your data with specific cell types
chosen_cell_type = ['neutrophil', 'macrophage', 'plasma']
filtered_cell_type_df = avg_gene_expr_lung[chosen_cell_type]

display(filtered_cell_type_df)

      neutrophil  macrophage    plasma
TP53    0.054815    0.132754  0.038301
KRAS    1.529643    0.489622  0.243355
EGFR    0.016721    0.011413  0.031597
ALK     0.000000    0.013633  0.000000

### **Output**
`filtered_cell_type_df` gives a *Pandas DataFrame* where:
* Each row represents a gene.  
* Each column corresponds to a cell type.
* The values indicate the average gene expression (measured in counts per ten thousand, or cptt).
* only selected cell types (*'neutrophil', 'macrophage', 'plasma'*) from the `avg_gene_expr_lung` are displayed.

## **5.1 Sorting gene expression by cell type**

This example shows how to sort `avg_gene_expr_lung` by the average gene expression in a specific cell type (neutrophils), in ascending order.

In [4]:
sorted_by_neutrophil = avg_gene_expr_lung.sort_values(by='neutrophil')

display(sorted_by_neutrophil)

,neutrophil,basophil,monocyte,macrophage,dendritic,B,plasma,T,NK,plasmacytoid,...,capillary,CAP2,lymphatic,fibroblast,alveolar fibroblast,smooth muscle,vascular smooth muscle,pericyte,mesothelial,ionocyte
COL13A1,0.000000,0.222863,0.000000,0.000711,0.000000,0.000000,0.002205,0.000000,0.029147,0.000000,...,0.003937,0.000000,0.000000,0.005113,0.446961,0.000000,0.131642,0.067960,0.000000,0.000000
COL14A1,0.000000,0.000000,0.001422,0.001362,0.000000,0.000000,0.002607,0.000000,0.000000,0.000000,...,0.007525,0.026666,0.059648,1.110076,1.226022,1.033389,2.108460,0.033580,0.000000,0.000000
PDGFRA,0.000000,0.000000,0.000965,0.002414,0.003172,0.000000,0.000000,0.005035,0.000000,0.000000,...,0.011427,0.002920,0.000000,1.772957,3.724075,0.128634,0.059852,0.000000,0.332479,0.000000
GZMA,0.013437,0.142837,0.174047,0.029326,0.020453,0.025113,0.063292,9.006065,19.687157,0.000000,...,0.044351,0.042996,0.073877,0.029919,0.081036,0.119041,0.000000,0.460141,0.044982,0.058806
TGFBI,0.065150,0.111107,1.802062,1.252701,2.190132,0.000000,0.083882,0.100460,0.326610,4.492828,...,0.045932,0.067610,0.521915,0.393191,0.175393,0.311884,0.258512,0.119010,0.404976,0.032419

### **Output**
`sorted_by_neutrophil` gives a *Pandas DataFrame* where:
* Each row represents a gene.  
* Each column corresponds to a cell type.
* The values indicate the average gene expression (measured in counts per ten thousand, or cptt).
* The order of the rows is based on the average gene expression in neutrophil in ascending order.

Additionally, `sort_values()` can return the output in descending order by setting the ascending parameter to False:

In [121]:
des_sorted_by_neutrophil = avg_gene_expr_lung.sort_values(by='neutrophil', ascending=False)

display(des_sorted_by_neutrophil)

,neutrophil,basophil,monocyte,macrophage,dendritic,B,plasma,T,NK,plasmacytoid,...,capillary,CAP2,lymphatic,fibroblast,alveolar fibroblast,smooth muscle,vascular smooth muscle,pericyte,mesothelial,ionocyte
KRAS,1.529643,0.436303,0.977728,0.489622,0.443576,0.562167,0.243355,0.826480,0.767580,0.467747,...,1.357422,1.346849,0.794639,0.249971,0.388602,0.582125,0.251247,0.708356,0.319821,0.714599
TP53,0.054815,0.119978,0.327787,0.132754,0.238697,0.178123,0.038301,0.202786,0.239634,0.074571,...,0.219169,0.126632,0.254856,0.175867,0.160920,0.110756,0.193365,0.252695,0.152536,0.227391
EGFR,0.016721,0.024823,0.028325,0.011413,0.000949,0.138468,0.031597,0.064145,0.051909,0.000000,...,0.579046,0.736705,0.085129,0.666291,0.720418,0.670286,0.528496,0.980535,0.225700,2.810568
ALK,0.000000,0.000000,0.001285,0.013633,0.000000,0.000000,0.000000,0.002077,0.000000,0.000000,...,0.001188,0.000000,0.000000,0.000689,0.004787,0.000000,0.000000,0.000000,0.000000,0.000000

### **Output**
`des_sorted_by_neutrophil` gives a *Pandas DataFrame* where:
* Each row represents a gene.  
* Each column corresponds to a cell type.
* The values indicate the average gene expression (measured in counts per ten thousand, or cptt).
* The order of the rows is based on the average gene expression in neutrophil in descending order.

## **5.2 Sorting gene expression by multiple cell types**

This example demonstrates how to sort `avg_gene_expr_lung` first by *neutrophils gene expression* and then by *basophils gene expression* in ascending order.

In [134]:
sorted_by_neutrophil_basophil = avg_gene_expr_lung.sort_values(by=['neutrophil', 'basophil'])

display(sorted_by_neutrophil_basophil)

,neutrophil,basophil,monocyte,macrophage,dendritic,B,plasma,T,NK,plasmacytoid,...,capillary,CAP2,lymphatic,fibroblast,alveolar fibroblast,smooth muscle,vascular smooth muscle,pericyte,mesothelial,ionocyte
ALK,0.000000,0.000000,0.001285,0.013633,0.000000,0.000000,0.000000,0.002077,0.000000,0.000000,...,0.001188,0.000000,0.000000,0.000689,0.004787,0.000000,0.000000,0.000000,0.000000,0.000000
EGFR,0.016721,0.024823,0.028325,0.011413,0.000949,0.138468,0.031597,0.064145,0.051909,0.000000,...,0.579046,0.736705,0.085129,0.666291,0.720418,0.670286,0.528496,0.980535,0.225700,2.810568
TP53,0.054815,0.119978,0.327787,0.132754,0.238697,0.178123,0.038301,0.202786,0.239634,0.074571,...,0.219169,0.126632,0.254856,0.175867,0.160920,0.110756,0.193365,0.252695,0.152536,0.227391
KRAS,1.529643,0.436303,0.977728,0.489622,0.443576,0.562167,0.243355,0.826480,0.767580,0.467747,...,1.357422,1.346849,0.794639,0.249971,0.388602,0.582125,0.251247,0.708356,0.319821,0.714599

### **Output**
`sorted_by_neutrophil_basophil` gives a *Pandas DataFrame* where:
* Each row represents a gene.  
* Each column corresponds to a cell type.
* The values indicate the average gene expression (measured in counts per ten thousand, or cptt).
* The order of the rows is based on the average gene expression firstly by neutrophil gene expression then by basophil, in ascending order.

This example demonstrates how to filter `avg_gene_expr_lung` to display only the selected cell types (*neutrophil*, *macrophage*, *plasma*).

In [44]:
# Filter your data with specific cell types
chosen_cell_type = ['neutrophil', 'macrophage', 'plasma']
filtered_cell_type_df = avg_gene_expr_lung[chosen_cell_type]

display(filtered_cell_type_df)

         neutrophil  macrophage    plasma
COL13A1    0.000000    0.000711  0.002205
COL14A1    0.000000    0.001362  0.002607
TGFBI      0.065150    1.252701  0.083882
PDGFRA     0.000000    0.002414  0.000000
GZMA       0.013437    0.029326  0.063292

### **Output**
`filtered_cell_type_df` gives a *Pandas DataFrame* where:
* Each row represents a gene.  
* Each column corresponds to a cell type.
* The values indicate the average gene expression (measured in counts per ten thousand, or cptt).
* only selected cell types (*'neutrophil', 'macrophage', 'plasma'*) from the `avg_gene_expr_lung` are displayed.

## **5.3 Sorting gene expression across multiple organs**

This example calculates and displays the *average gene expression* for five specified genes (*COL13A1*, *COL14A1*, *TGFBI*, *PDGFRA*, *GZMA*) across three human organs: *lung*, *gut*, and *liver*. The gene expression data for each organ is sorted by the values in *neutrophils* and *T cells* before being displayed.

In [53]:
organ_list = api.organs(organism="h_sapiens")

# loop through organ_list and display the results
for organ in organ_list:
    avg_gene_expr = api.average(
        organism = "h_sapiens", 
        organ = organ, 
        features = ['MTRNR2L12', 'AL512646.1', 'FP671120.5'], 
        measurement_type = 'gene_expression'
    )

    # Display the result
    print(f'Everage gene expression in human {organ}:')
    display(avg_gene_expr)
    # display(avg_gene_expr.sort_values(by=['neutrophil', 'T'])

Everage gene expression in human bladder:

,mast,macrophage,B,plasma,T,NK,plasmacytoid,urothelial,venous,capillary,lymphatic,fibroblast,smooth muscle,pericyte
MTRNR2L12,0.040105,0.121860,0.132304,0.016499,0.013802,0.052788,0.002277,0.059001,0.092321,0.041095,0.083313,0.058918,0.034633,0.051836
AL512646.1,0.035943,0.038304,0.022516,0.003811,0.000003,0.010509,0.009106,0.009846,0.013450,0.000868,0.019044,0.003351,0.013949,0.001608
FP671120.5,0.037544,0.052078,0.109802,0.039630,0.001136,0.003897,0.038702,0.061551,0.125526,0.004339,0.208300,0.036039,0.009927,0.024970

Everage gene expression in human blood:

,HSC,neutrophil,basophil,myeloid,monocyte,macrophage,dendritic,erythrocyte,B,plasma,T,NK,plasmacytoid,platelet
MTRNR2L12,0.042015,0.020157,0.04958,0.0,0.064458,0.003231,0.035253,0.006407,0.024542,0.026737,0.021280,0.020722,0.0,0.165943
AL512646.1,0.001165,0.036670,0.00000,0.0,0.145861,0.000000,0.000000,0.004813,0.004529,0.040637,0.002428,0.000875,0.0,0.002268
FP671120.5,0.058010,0.016955,0.00000,0.0,0.068890,0.013620,0.000000,0.008137,0.086548,0.006233,0.122227,0.037445,0.0,0.080209

Everage gene expression in human colon:

,neutrophil,mast,monocyte,B,plasma,T,goblet,brush,crypt,transit amp,enterocyte,paneth,venous,capillary,fibroblast,enteroendocrine
MTRNR2L12,0.878699,0.0,0.025914,0.030038,0.012355,0.024335,2.114801,2.636931,0.351932,0.056754,0.674713,0.123892,0.000000,0.0,0.060827,0.218810
AL512646.1,0.055621,0.0,0.000000,0.000000,0.000000,0.000000,0.035407,0.328170,0.006913,0.000898,0.014697,0.000000,0.000000,0.0,0.000169,0.001798
FP671120.5,0.040737,0.0,0.004727,0.003165,0.000000,0.002037,0.422802,1.238326,0.056464,0.006978,0.048138,0.000000,0.085853,0.0,0.005391,0.000000

Everage gene expression in human eye:

,mast,monocyte,macrophage,dendritic,erythrocyte,B,plasma,T,glial,acinar,...,keratocyte,adipocyte,neuron,photoreceptor,muller,limbal,lacrimal,retinal pigment,horizontal,ganglion
MTRNR2L12,0.016971,0.015319,0.047667,0.050238,0.033083,0.087029,0.083818,0.178030,0.041987,0.636664,...,0.026781,0.033941,0.073060,0.016360,0.055366,0.054655,0.073064,0.004403,0.0,0.0
AL512646.1,0.016971,0.017728,0.030061,0.006266,0.001086,0.008658,0.029437,0.034737,0.011517,0.256456,...,0.002609,0.000000,0.007731,0.000823,0.004273,0.000000,0.000000,0.000760,0.0,0.0
FP671120.5,0.158400,0.196810,0.078597,0.036654,0.003069,0.293075,0.006035,0.152271,0.051087,0.131996,...,0.004206,0.000000,0.006917,0.005725,0.012020,0.013463,0.000000,0.014172,0.0,0.0

Everage gene expression in human fat:

,neutrophil,mast,macrophage,B,plasma,T,NK,arterial,venous,capillary,lymphatic,fibroblast,smooth muscle
MTRNR2L12,0.008249,0.101713,0.036114,0.477936,0.050222,0.013784,0.051818,0.013512,0.018008,0.006134,0.001504,0.025964,0.011467
AL512646.1,0.000000,0.024245,0.008542,0.847171,0.005092,0.001320,0.003557,0.007916,0.002007,0.000016,0.000317,0.000465,0.000150
FP671120.5,0.003910,0.010847,0.022777,0.256812,0.010878,0.025936,0.101243,0.025452,0.018020,0.000109,0.007639,0.004601,0.004687

Everage gene expression in human gut:

,neutrophil,mast,monocyte,B,plasma,T,goblet,brush,crypt,transit amp,enterocyte,paneth,venous,lymphatic,fibroblast,enteroendocrine
MTRNR2L12,0.098096,0.0,0.021579,0.041577,0.006942,0.021134,0.100320,0.071035,0.124631,0.177001,0.561389,0.141057,0.105221,0.563677,0.036005,0.045235
AL512646.1,0.081317,0.0,0.000000,0.000279,0.000000,0.000000,0.002903,0.000000,0.014763,0.014392,0.062879,0.007720,0.000000,0.000000,0.000119,0.008978
FP671120.5,0.020003,0.0,0.000000,0.003524,0.000000,0.002405,0.027964,0.013543,0.132837,0.098455,0.211932,0.036896,0.000000,0.000000,0.000476,0.032671

Everage gene expression in human heart:

            macrophage  coronary  fibroblast  cardiomyocyte  smooth muscle
MTRNR2L12     0.065913  0.014408    0.028127       0.009999       0.031971
AL512646.1    0.713226  0.002436    0.010123       0.000255       0.008121
FP671120.5    0.174265  0.016833    0.050259       0.004069       0.037897

Everage gene expression in human kidney:

            macrophage         B         T        NK  epithelial  capillary
MTRNR2L12     0.074447  0.134446  0.100383  0.093024    0.041235   0.147291
AL512646.1    0.030150  0.014533  0.010992  0.011832    0.009351   0.000000
FP671120.5    0.028511  0.199491  0.179547  0.188795    0.033847   0.000000

Everage gene expression in human liver:

,neutrophil,monocyte,macrophage,dendritic,erythrocyte,plasma,T,NK,epithelial,cholangiocyte,capillary,lymphatic,fibroblast,hepatocyte
MTRNR2L12,1.004547,0.012201,0.081941,0.055378,0.027204,0.015974,0.048050,0.045191,0.0,0.105617,0.039465,0.060688,0.054623,0.019778
AL512646.1,1.257892,0.001236,0.010397,0.002707,0.001182,0.003812,0.004918,0.001650,0.0,0.005423,0.002305,0.000000,0.002550,0.004608
FP671120.5,1.372942,0.005936,0.096488,0.067010,0.016033,0.056380,0.018628,0.146617,0.0,0.044807,0.019722,0.000000,0.058874,0.022207

Everage gene expression in human lung:

,neutrophil,basophil,monocyte,macrophage,dendritic,B,plasma,T,NK,plasmacytoid,...,capillary,CAP2,lymphatic,fibroblast,alveolar fibroblast,smooth muscle,vascular smooth muscle,pericyte,mesothelial,ionocyte
MTRNR2L12,0.360152,0.003441,0.011611,0.014181,0.005101,0.010768,0.026876,0.013848,0.000409,0.000000,...,0.015733,0.007940,0.005639,0.185228,0.038251,0.019525,0.002117,0.006557,0.049525,0.0
AL512646.1,0.458429,0.002841,0.040241,0.001399,0.007502,0.002712,0.000281,0.001204,0.005510,0.009050,...,0.004600,0.001857,0.007518,0.022937,0.014955,0.001416,0.003079,0.001250,0.000000,0.0
FP671120.5,0.149891,0.013807,0.019843,0.005380,0.036892,0.050912,0.118577,0.016912,0.020365,0.053477,...,0.029007,0.017389,0.155473,0.337506,0.087515,0.046992,0.042961,0.025072,0.017725,0.0

Everage gene expression in human lymphnode:

,HSC,neutrophil,mast,monocyte,macrophage,dendritic,erythrocyte,B,plasma,T,NK,NKT,ILC,plasmacytoid,lymphatic,fibroblast
MTRNR2L12,0.0,0.0,0.012502,0.025722,0.018707,0.033145,0.265811,0.032487,0.012158,0.019239,0.015790,0.036665,0.067851,0.0,0.0,0.0
AL512646.1,0.0,0.0,0.008761,0.017037,0.000167,0.002325,0.875835,0.003684,0.001695,0.001602,0.000260,0.000000,0.014522,0.0,0.0,0.0
FP671120.5,0.0,0.0,0.049608,0.033740,0.003653,0.046589,0.710660,0.039015,0.044549,0.038780,0.010779,0.000000,0.200118,0.0,0.0,0.0

Everage gene expression in human mammary:

,mast,macrophage,B,plasma,T,NK,basal,luminal,arterial,venous,lymphatic,fibroblast,vascular smooth muscle,pericyte
MTRNR2L12,0.127969,0.233229,0.76191,0.107960,0.052822,0.309942,0.004474,0.061111,0.019396,0.017262,0.059685,0.038446,0.007031,0.004998
AL512646.1,0.000000,0.089438,0.01811,0.000160,0.002965,0.006798,0.003182,0.003911,0.000812,0.016497,0.003850,0.005286,0.000000,0.000781
FP671120.5,0.000000,0.061113,0.24405,0.097953,0.050455,0.927118,0.001176,0.028851,0.013249,0.021357,0.021228,0.030421,0.000000,0.000520

Everage gene expression in human marrow:

,HSC,neutrophil,granulocyte,myeloid,monocyte,macrophage,erythroid,erythrocyte,B,plasma,T,NK
MTRNR2L12,0.094203,0.089975,0.155448,0.031207,0.313646,0.009447,0.045501,0.007760,0.061048,0.097468,0.038610,0.067577
AL512646.1,0.039823,0.290600,0.361784,0.005861,0.481665,0.002090,0.007636,0.008655,0.012652,0.027081,0.013042,0.009151
FP671120.5,0.096421,0.022508,0.064031,0.026247,0.199807,0.027744,0.041949,0.005074,0.095549,0.136016,0.125061,0.103930

Everage gene expression in human muscle:

,mast,macrophage,erythrocyte,T,NKT,arterial,capillary,lymphatic,fibroblast,tendon,striated muscle,smooth muscle,pericyte,mesothelial,satellite
MTRNR2L12,0.455624,0.266389,0.466717,0.287951,0.063669,0.062779,0.165217,0.709055,0.020465,0.102324,0.007643,0.265063,0.107480,0.320110,0.093395
AL512646.1,0.023041,0.107747,0.008215,0.022989,0.037078,0.001868,0.024431,0.029068,0.000032,0.009450,0.009094,0.006589,0.007679,0.002129,0.027172
FP671120.5,0.203354,0.155269,0.417190,0.163059,0.416783,0.029179,0.108256,0.136138,0.001452,0.084874,0.098967,0.066023,0.062713,0.012776,0.059419

Everage gene expression in human pancreas:

,mast,myeloid,B,plasma,T,NK,ductal,acinar,venous,capillary,lymphatic,fibroblast,stellate,alpha,beta,PP,delta
MTRNR2L12,0.068819,0.008557,0.056874,0.0,0.016086,0.0,0.029761,0.033432,0.003558,0.00000,0.0,0.123861,0.003902,0.089435,0.014229,0.400545,0.0
AL512646.1,0.085366,0.074373,0.076321,0.0,0.001048,0.0,0.016639,0.196115,0.000000,0.00000,0.0,0.000000,0.001344,0.173258,0.001572,0.298676,0.0
FP671120.5,0.292742,0.009939,0.418054,0.0,0.009007,0.0,0.025249,0.072510,0.004142,0.01084,0.0,0.000000,0.009746,0.063812,0.023504,0.362456,0.0

Everage gene expression in human prostate:

,neutrophil,mast,myeloid,monocyte,macrophage,erythroid,T,NKT,epithelial,hillock-club,hillock-basal,club,acinar,basal,luminal,arterial,venous,lymphatic,fibroblast,smooth muscle
MTRNR2L12,0.207091,0.0,0.016093,1.367727,0.015773,0.027447,0.053669,0.061961,0.019505,0.027118,0.065823,0.052338,0.055695,0.038572,0.034803,0.02501,0.051809,0.000000,0.0139,0.05753
AL512646.1,0.000000,0.0,0.000000,0.285360,0.000000,0.000000,0.002183,0.004168,0.000564,0.000000,0.000000,0.000000,0.000000,0.000892,0.000000,0.00000,0.000000,0.000000,0.0000,0.00000
FP671120.5,0.000000,0.0,0.000000,0.885620,0.000000,0.000000,0.050057,0.081235,0.057450,0.000000,0.005761,0.002064,0.000000,0.015041,0.001428,0.00000,0.000000,0.062488,0.0000,0.00000

Everage gene expression in human salivary:

,neutrophil,monocyte,macrophage,B,plasma,T,NK,ductal,acinar,basal,myoepithelial,arterial,venous,capillary,lymphatic,fibroblast,pericyte,ionocyte
MTRNR2L12,0.020969,0.012971,0.022926,0.024548,0.002834,0.049653,0.008621,0.039484,0.009365,0.046037,0.030518,0.0,0.0,0.053769,0.021678,0.085228,0.034389,0.020411
AL512646.1,0.000000,0.000000,0.000000,0.002487,0.000000,0.007578,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.004072,0.000000,0.000000
FP671120.5,0.000000,0.000000,0.010763,0.022904,0.002692,0.106713,0.009249,0.010143,0.004635,0.011743,0.014962,0.0,0.0,0.000000,0.016262,0.073411,0.012119,0.000000

Everage gene expression in human skin:

,mast,macrophage,dendritic,B,plasma,T,NK,NKT,epithelial,melanocyte,arterial,venous,capillary,lymphatic,fibroblast,striated muscle,smooth muscle
MTRNR2L12,0.066609,0.121908,0.071537,0.092447,0.010605,0.023701,0.028244,0.007368,0.517292,0.267094,0.023582,0.134501,0.066380,0.072889,0.010785,0.076633,0.0
AL512646.1,0.019756,0.060804,0.030808,0.009424,0.002006,0.001929,0.003305,0.000301,0.479155,0.011963,0.008843,0.009753,0.001652,0.007291,0.000242,0.001546,0.0
FP671120.5,0.284188,0.200612,0.202820,0.222958,0.081198,0.064494,0.052037,0.038489,0.215930,0.165875,0.025350,0.065052,0.038713,0.046530,0.008524,0.029104,0.0

Everage gene expression in human spleen:

,HSC,neutrophil,monocyte,macrophage,dendritic,erythrocyte,B,plasma,T,NK,NKT,ILC,plasmacytoid,platelet,acinar,capillary
MTRNR2L12,0.002817,0.037333,0.082009,0.012586,0.024289,0.000661,0.026614,0.014670,0.021985,0.010928,0.034035,0.002627,0.019388,0.119196,0.007737,0.043320
AL512646.1,0.000000,0.078561,0.130851,0.007867,0.007510,0.030750,0.011693,0.006954,0.003164,0.003413,0.009282,0.001320,0.005501,0.000602,0.000000,0.000000
FP671120.5,0.000000,0.013268,0.068260,0.007635,0.034397,0.013392,0.064365,0.038624,0.050796,0.029637,0.068436,0.012394,0.099740,0.047856,0.016992,0.141481

Everage gene expression in human thymus:

,mast,monocyte,macrophage,dendritic,erythrocyte,B,plasma,thymocyte,T,NK,...,ILC,mTEC,arterial,venous,capillary,lymphatic,fibroblast,striated muscle,vascular smooth muscle,mesothelial
MTRNR2L12,0.015019,0.049541,0.021284,0.0,0.238227,0.021592,0.016196,0.004470,0.009914,0.081501,...,0.010229,0.023686,0.013244,0.036467,0.044756,0.004901,0.028347,0.056554,0.046097,0.026277
AL512646.1,0.009011,0.030729,0.004620,0.0,0.005109,0.000964,0.000304,0.000000,0.000004,0.000107,...,0.000000,0.000687,0.000000,0.001900,0.005055,0.000000,0.000932,0.006564,0.002261,0.000000
FP671120.5,0.027034,0.028940,0.025587,0.0,0.105706,0.002984,0.007510,0.004349,0.003893,0.009806,...,0.001645,0.013787,0.001929,0.033537,0.049035,0.003518,0.025227,0.138604,0.042371,0.041293

Everage gene expression in human tongue:

,neutrophil,macrophage,dendritic,B,T,NK,epithelial,keratinocyte,basal,arterial,venous,capillary,lymphatic,fibroblast,striated muscle,pericyte,schwann
MTRNR2L12,0.421631,0.151765,0.119968,0.0,0.058128,0.462927,0.002246,0.013925,0.113814,0.037258,0.104963,0.000339,0.120080,0.133245,0.061096,0.135843,0.047141
AL512646.1,0.224279,0.068190,0.052349,0.0,0.013162,0.122612,0.000000,0.007331,0.024756,0.003567,0.007935,0.000678,0.006320,0.043729,0.007173,0.053588,0.000000
FP671120.5,0.187259,0.022938,0.035543,0.0,0.033582,0.256381,0.003542,0.009015,0.059897,0.005945,0.011426,0.016538,0.039445,0.046090,0.060427,0.031249,0.000000

Everage gene expression in human trachea:

,neutrophil,mast,macrophage,B,plasma,T,goblet,ciliated,basal,serous,mucous,venous,capillary,lymphatic,fibroblast,smooth muscle,ionocyte
MTRNR2L12,0.028558,0.018349,0.020212,0.020175,0.058480,0.001359,0.240449,0.484247,0.027847,0.095926,0.212741,0.386744,0.226318,0.0,0.017832,0.036696,0.075616
AL512646.1,0.138140,0.006608,0.045739,0.001265,0.058129,0.000000,0.015729,0.021314,0.002233,0.004574,0.090114,0.007723,0.006527,0.0,0.001499,0.001659,0.003563
FP671120.5,0.033274,0.057668,0.070120,0.012643,0.169032,0.000227,0.166679,0.217794,0.024170,0.070943,0.100388,0.167579,0.098107,0.0,0.038148,0.163210,0.035234

Everage gene expression in human uterus:

,macrophage,B,T,NK,epithelial,ciliated,arterial,venous,capillary,lymphatic,fibroblast,smooth muscle,vascular smooth muscle,pericyte
MTRNR2L12,0.025299,0.0,0.034341,0.011529,0.297524,0.052369,0.002598,0.027446,0.014444,0.030962,0.042971,0.019226,0.008346,0.003260
AL512646.1,0.019101,0.0,0.001258,0.000531,0.009079,0.005499,0.000000,0.000000,0.000293,0.002616,0.015282,0.000000,0.000000,0.000246
FP671120.5,0.052155,0.0,0.038640,0.041981,0.102291,0.063255,0.000000,0.006557,0.007108,0.032916,0.027862,0.000000,0.000000,0.004576

### **Output**
This code gives 3 *Pandas DataFrame* where:
* Each *pandas Dataframe* focus on one chosen organ.
* For each *Pandas Dataframe*, each row represents a gene.  
* For each *Pandas Dataframe*, each column corresponds to a cell type.
* For each *Pandas Dataframe*, the values indicate the average gene expression (measured in counts per ten thousand, or cptt).
* For each *Pandas Dataframe*, the order of the rows is based on the average gene expression firstly by neutrophil gene expression then by t cell, in ascending order.



## **Conclusion**



This tutorial provide the some basic usage of `average` in *atlasapprox*. Thank you for using *atlasapprox* API, for more detailed information, please refer to the [official documentation](https://atlasapprox.readthedocs.io/en/latest/python/index.html).